on:
  push:
    branches:
      - 'main'

jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - name: checkout repository
        uses: actions/checkout@v4

      - name: validate gradle wrapper
        uses: gradle/actions/wrapper-validation@v4

      - name: setup jdk
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'microsoft'

      - name: make gradle wrapper executable
        run: chmod +x ./gradlew

      - name: build
        run: ./gradlew build

      - name: capture build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: Artifacts
          path: build/libs/

      - name: Upload to Modrinth, Curseforge, and Github
        uses: Kir-Antipov/mc-publish@v3.3
        with:
          modrinth-id: mn0GGHQK
          modrinth-token: ${{ secrets.MODRINTH_TOKEN }}

          curseforge-id: 1270564
          curseforge-token: ${{ secrets.CURSEFORGE_TOKEN }}

          github-token: ${{ secrets.GH_TOKEN }}

          files: build/libs/!(*-@(dev|sources|all)).jar
